// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: bill/bill.proto

package bill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBillRequest) Reset() {
	*x = CreateBillRequest{}
	mi := &file_bill_bill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillRequest) ProtoMessage() {}

func (x *CreateBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bill_bill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillRequest.ProtoReflect.Descriptor instead.
func (*CreateBillRequest) Descriptor() ([]byte, []int) {
	return file_bill_bill_proto_rawDescGZIP(), []int{0}
}

type CreateBillReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBillReply) Reset() {
	*x = CreateBillReply{}
	mi := &file_bill_bill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBillReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillReply) ProtoMessage() {}

func (x *CreateBillReply) ProtoReflect() protoreflect.Message {
	mi := &file_bill_bill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillReply.ProtoReflect.Descriptor instead.
func (*CreateBillReply) Descriptor() ([]byte, []int) {
	return file_bill_bill_proto_rawDescGZIP(), []int{1}
}

var File_bill_bill_proto protoreflect.FileDescriptor

var file_bill_bill_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x62, 0x69, 0x6c, 0x6c, 0x2f, 0x62, 0x69, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32,
	0x44, 0x0a, 0x04, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x3c, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x17, 0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x69, 0x6e, 0x6f, 0x4d, 0x61, 0x6d, 0x62, 0x61, 0x2f, 0x6c, 0x61,
	0x7a, 0x79, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x6c,
	0x6c, 0x3b, 0x62, 0x69, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bill_bill_proto_rawDescOnce sync.Once
	file_bill_bill_proto_rawDescData = file_bill_bill_proto_rawDesc
)

func file_bill_bill_proto_rawDescGZIP() []byte {
	file_bill_bill_proto_rawDescOnce.Do(func() {
		file_bill_bill_proto_rawDescData = protoimpl.X.CompressGZIP(file_bill_bill_proto_rawDescData)
	})
	return file_bill_bill_proto_rawDescData
}

var file_bill_bill_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bill_bill_proto_goTypes = []any{
	(*CreateBillRequest)(nil), // 0: bill.CreateBillRequest
	(*CreateBillReply)(nil),   // 1: bill.CreateBillReply
}
var file_bill_bill_proto_depIdxs = []int32{
	0, // 0: bill.Bill.CreateBill:input_type -> bill.CreateBillRequest
	1, // 1: bill.Bill.CreateBill:output_type -> bill.CreateBillReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bill_bill_proto_init() }
func file_bill_bill_proto_init() {
	if File_bill_bill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bill_bill_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bill_bill_proto_goTypes,
		DependencyIndexes: file_bill_bill_proto_depIdxs,
		MessageInfos:      file_bill_bill_proto_msgTypes,
	}.Build()
	File_bill_bill_proto = out.File
	file_bill_bill_proto_rawDesc = nil
	file_bill_bill_proto_goTypes = nil
	file_bill_bill_proto_depIdxs = nil
}
