// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: transaction.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTransaction = `-- name: DeleteTransaction :exec
UPDATE transactions SET 
is_deleted = true,
updated_by = $2,
updated_at = $3
WHERE id = $1
`

type DeleteTransactionParams struct {
	ID        string
	UpdatedBy pgtype.Text
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UpdatedBy, arg.UpdatedAt)
	return err
}

const getTransactionById = `-- name: GetTransactionById :one
SELECT id, name, type, date, amount, remark, category_id, is_deleted, created_by, created_at, updated_by, updated_at FROM transactions WHERE id = $1 AND is_deleted = false LIMIT 1
`

func (q *Queries) GetTransactionById(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionById, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Date,
		&i.Amount,
		&i.Remark,
		&i.CategoryID,
		&i.IsDeleted,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionListByCreator = `-- name: GetTransactionListByCreator :many
SELECT id, name, type, date, amount, remark, category_id, is_deleted, created_by, created_at, updated_by, updated_at FROM transactions WHERE created_by = $1 AND is_deleted = false ORDER BY date DESC, created_at DESC
`

func (q *Queries) GetTransactionListByCreator(ctx context.Context, createdBy pgtype.Text) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionListByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Date,
			&i.Amount,
			&i.Remark,
			&i.CategoryID,
			&i.IsDeleted,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (
  id, 
  name, 
  amount,
  type,
  date,
  remark,
  category_id,
  created_by,
  created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertTransactionParams struct {
	ID         string
	Name       string
	Amount     pgtype.Numeric
	Type       pgtype.Int2
	Date       pgtype.Timestamp
	Remark     pgtype.Text
	CategoryID string
	CreatedBy  pgtype.Text
	CreatedAt  pgtype.Timestamp
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Type,
		arg.Date,
		arg.Remark,
		arg.CategoryID,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions SET 
name = $2,
amount = $3,
type = $4,
date = $5,
remark = $6,
category_id = $7,
updated_by = $8,
updated_at = $9
WHERE id = $1
`

type UpdateTransactionParams struct {
	ID         string
	Name       string
	Amount     pgtype.Numeric
	Type       pgtype.Int2
	Date       pgtype.Timestamp
	Remark     pgtype.Text
	CategoryID string
	UpdatedBy  pgtype.Text
	UpdatedAt  pgtype.Timestamp
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.Exec(ctx, updateTransaction,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Type,
		arg.Date,
		arg.Remark,
		arg.CategoryID,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const updateTransactionAmount = `-- name: UpdateTransactionAmount :exec
UPDATE transactions SET 
amount = $2,
updated_by = $3,
updated_at = $4
WHERE id = $1
`

type UpdateTransactionAmountParams struct {
	ID        string
	Amount    pgtype.Numeric
	UpdatedBy pgtype.Text
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) UpdateTransactionAmount(ctx context.Context, arg UpdateTransactionAmountParams) error {
	_, err := q.db.Exec(ctx, updateTransactionAmount,
		arg.ID,
		arg.Amount,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const updateTransactionCategory = `-- name: UpdateTransactionCategory :exec
UPDATE transactions SET 
category_id = $2,
updated_by = $3,
updated_at = $4
WHERE id = $1
`

type UpdateTransactionCategoryParams struct {
	ID         string
	CategoryID string
	UpdatedBy  pgtype.Text
	UpdatedAt  pgtype.Timestamp
}

func (q *Queries) UpdateTransactionCategory(ctx context.Context, arg UpdateTransactionCategoryParams) error {
	_, err := q.db.Exec(ctx, updateTransactionCategory,
		arg.ID,
		arg.CategoryID,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const updateTransactionDate = `-- name: UpdateTransactionDate :exec
UPDATE transactions SET 
date = $2,
updated_by = $3,
updated_at = $4
WHERE id = $1
`

type UpdateTransactionDateParams struct {
	ID        string
	Date      pgtype.Timestamp
	UpdatedBy pgtype.Text
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) UpdateTransactionDate(ctx context.Context, arg UpdateTransactionDateParams) error {
	_, err := q.db.Exec(ctx, updateTransactionDate,
		arg.ID,
		arg.Date,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const updateTransactionName = `-- name: UpdateTransactionName :exec
UPDATE transactions SET 
name = $2,
updated_by = $3,
updated_at = $4
WHERE id = $1
`

type UpdateTransactionNameParams struct {
	ID        string
	Name      string
	UpdatedBy pgtype.Text
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) UpdateTransactionName(ctx context.Context, arg UpdateTransactionNameParams) error {
	_, err := q.db.Exec(ctx, updateTransactionName,
		arg.ID,
		arg.Name,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const updateTransactionRemark = `-- name: UpdateTransactionRemark :exec
UPDATE transactions SET 
remark = $2,
updated_by = $3,
updated_at = $4
WHERE id = $1
`

type UpdateTransactionRemarkParams struct {
	ID        string
	Remark    pgtype.Text
	UpdatedBy pgtype.Text
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) UpdateTransactionRemark(ctx context.Context, arg UpdateTransactionRemarkParams) error {
	_, err := q.db.Exec(ctx, updateTransactionRemark,
		arg.ID,
		arg.Remark,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const updateTransactionType = `-- name: UpdateTransactionType :exec
UPDATE transactions SET 
type = $2,
updated_by = $3,
updated_at = $4
WHERE id = $1
`

type UpdateTransactionTypeParams struct {
	ID        string
	Type      pgtype.Int2
	UpdatedBy pgtype.Text
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) UpdateTransactionType(ctx context.Context, arg UpdateTransactionTypeParams) error {
	_, err := q.db.Exec(ctx, updateTransactionType,
		arg.ID,
		arg.Type,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}
