// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/vinoMamba/lazyledger/internal/biz"
	"github.com/vinoMamba/lazyledger/internal/conf"
	"github.com/vinoMamba/lazyledger/internal/repository"
	"github.com/vinoMamba/lazyledger/internal/server"
	"github.com/vinoMamba/lazyledger/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	queries, cleanup, err := repository.NewData(data, logger)
	if err != nil {
		return nil, nil, err
	}
	userBiz := biz.NewUserBiz(queries)
	userService := service.NewUserService(userBiz)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	httpServer := server.NewHTTPServer(confServer, userService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
