// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/vinoMamba/lazyledger/app/user/internal/conf"
	"github.com/vinoMamba/lazyledger/app/user/internal/server"
	"github.com/vinoMamba/lazyledger/app/user/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	userService := service.NewUserService()
	grpcServer := server.NewGRPCServer(confServer, logger, userService)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
