// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v3"
	"github.com/spf13/viper"
	"github.com/vinoMamba/lazyledger/internal/biz"
	"github.com/vinoMamba/lazyledger/internal/handler"
	"github.com/vinoMamba/lazyledger/internal/repository"
	"github.com/vinoMamba/lazyledger/internal/server"
	"github.com/vinoMamba/lazyledger/pkg/jwt"
	"github.com/vinoMamba/lazyledger/pkg/sid"
)

// Injectors from wire.go:

func NewApp(viperViper *viper.Viper) (*fiber.App, func(), error) {
	dbtx := repository.NewConn(viperViper)
	queries := repository.New(dbtx)
	sidSid := sid.NewSid()
	jwtJWT := jwt.NewJWT(viperViper)
	bizBiz := biz.NewBiz(queries, sidSid, jwtJWT, viperViper)
	userBiz := biz.NewUserBiz(bizBiz)
	userHandler := handler.NewUserHandler(userBiz)
	categoryBiz := biz.NewCategoryBiz(bizBiz)
	categoryHandler := handler.NewCategoryHandler(categoryBiz)
	tagBiz := biz.NewTagBiz(bizBiz)
	tagHandler := handler.NewTagHandler(tagBiz)
	app := server.NewHttpServer(userHandler, userBiz, jwtJWT, categoryHandler, tagHandler)
	return app, func() {
	}, nil
}
